# -------- Build Stage --------
FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# -------- Runtime Stage --------
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD sh -c "java -Xms256m -Xmx512m -jar app.jar --server.port=${PORT} --server.address=0.0.0.0"